//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pendulum_Form.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pendulum_Form.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Amaranthe {
            get {
                object obj = ResourceManager.GetObject("Amaranthe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Albums(id,artist,title,release) VALUES (&apos;ama1&apos;,&apos;Amaranthe&apos;,&apos;Amaranthe&apos;,&apos;2011-04-13&apos;);
        ///INSERT INTO Albums(id,artist,title,release) VALUES (&apos;ama2&apos;,&apos;Amaranthe&apos;,&apos;The Nexus&apos;,&apos;2013-03-19&apos;);
        ///INSERT INTO Albums(id,artist,title,release) VALUES (&apos;ama3&apos;,&apos;Amaranthe&apos;,&apos;Massive Addictive&apos;,&apos;2014-10-21&apos;);
        ///INSERT INTO Albums(id,artist,title,release) VALUES (&apos;ama4&apos;,&apos;Amaranthe&apos;,&apos;Maximalism&apos;,&apos;2016-10-21&apos;);
        ///INSERT INTO Tracks(title,length,album,url) VALUES (&apos;Leave Everything Behind&apos;,&apos;03:19:00&apos;,&apos;ama1&apos;,&apos;null&apos;);
        ///IN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Amaranthe_Adatok {
            get {
                return ResourceManager.GetString("Amaranthe_Adatok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hold_your_colour {
            get {
                object obj = ResourceManager.GetObject("Hold_your_colour", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Immersion {
            get {
                object obj = ResourceManager.GetObject("Immersion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap In_silico {
            get {
                object obj = ResourceManager.GetObject("In_silico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Massive_addictive {
            get {
                object obj = ResourceManager.GetObject("Massive_addictive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Maximalism {
            get {
                object obj = ResourceManager.GetObject("Maximalism", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] music {
            get {
                object obj = ResourceManager.GetObject("music", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] music_log {
            get {
                object obj = ResourceManager.GetObject("music_log", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nexus {
            get {
                object obj = ResourceManager.GetObject("Nexus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Albums(id,artist,title,release) VALUES (&apos;pnd1&apos;,&apos;Pendulum&apos;,&apos;Hold Your Colour&apos;,&apos;2005-07-25&apos;);
        ///INSERT INTO Albums(id,artist,title,release) VALUES (&apos;pnd2&apos;,&apos;Pendulum&apos;,&apos;In Silico&apos;,&apos;2008-05-12&apos;);
        ///INSERT INTO Albums(id,artist,title,release) VALUES (&apos;pnd3&apos;,&apos;Pendulum&apos;,&apos;Immersion&apos;,&apos;2010-05-24&apos;);
        ///INSERT INTO Tracks(title,length,album,url) VALUES (&apos;Prelude&apos;,&apos;00:52:00&apos;,&apos;pnd1&apos;,&apos;null&apos;);
        ///INSERT INTO Tracks(title,length,album,url) VALUES (&apos;Slam&apos;,&apos;05:44:00&apos;,&apos;pnd1&apos;,&apos;gIOQfdn9L9c&apos;);
        ///INSERT INTO Tracks(title,leng [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pendulum_Adatok {
            get {
                return ResourceManager.GetString("Pendulum_Adatok", resourceCulture);
            }
        }
    }
}
