INSERT INTO Albums(id,artist,title,release) VALUES ('ama1','Amaranthe','Amaranthe','2011-04-13');
INSERT INTO Albums(id,artist,title,release) VALUES ('ama2','Amaranthe','The Nexus','2013-03-19');
INSERT INTO Albums(id,artist,title,release) VALUES ('ama3','Amaranthe','Massive Addictive','2014-10-21');
INSERT INTO Albums(id,artist,title,release) VALUES ('ama4','Amaranthe','Maximalism','2016-10-21');
INSERT INTO Tracks(title,length,album,url) VALUES ('Leave Everything Behind','03:19:00','ama1','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Hunger','03:13:00','ama1','9y25snz83ms');
INSERT INTO Tracks(title,length,album,url) VALUES ('1.000.000 Lightyears','03:16:00','ama1','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Automatic','03:26:00','ama1','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('My Transition','03:50:00','ama1','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Amaranthine','03:30:00','ama1','D8lV1To-_fU');
INSERT INTO Tracks(title,length,album,url) VALUES ('Rain','03:45:00','ama1','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Call Out My Name','03:17:00','ama1','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Enter the Maze','04:05:00','ama1','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Directors Cut','04:44:00','ama1','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Act of Desperation','03:05:00','ama1','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Serendipity','03:26:00','ama1','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Afterlife','03:15:00','ama2','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Invincible','03:11:00','ama2','NnY8C77EQKU');
INSERT INTO Tracks(title,length,album,url) VALUES ('The Nexus','03:16:00','ama2','SxOybZcRXhI');
INSERT INTO Tracks(title,length,album,url) VALUES ('Theory of Everything','03:35:00','ama2','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Stardust','03:09:00','ama2','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Burn with Me','04:01:00','ama2','IEgkUKCwi30');
INSERT INTO Tracks(title,length,album,url) VALUES ('Mechanical Illusion','04:01:00','ama2','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Razorblade','03:05:00','ama2','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Future on Hold','03:17:00','ama2','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Electroheart','03:48:00','ama2','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Transhuman','03:55:00','ama2','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Infinity','03:05:00','ama2','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Dynamite','03:14:00','ama3','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Drop Dead Cynical','03:17:00','ama3','RdyExxpd3Pg');
INSERT INTO Tracks(title,length,album,url) VALUES ('Trinity','03:11:00','ama3','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Massive Addictive','03:29:00','ama3','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Digital World','03:17:00','ama3','z6PYAkXO-bU');
INSERT INTO Tracks(title,length,album,url) VALUES ('True','03:30:00','ama3','8bSq4eB9cO8');
INSERT INTO Tracks(title,length,album,url) VALUES ('Unreal','03:36:00','ama3','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Over and Done','03:38:00','ama3','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Danger Zone','03:01:00','ama3','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Skyline','03:39:00','ama3','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('An Ordinary Abnormality','03:28:00','ama3','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Exhale','03:43:00','ama3','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Maximize','03:10:00','ama4','nfk7YZJtmeo');
INSERT INTO Tracks(title,length,album,url) VALUES ('Boomerang','03:22:00','ama4','Wjdm5tJ5NiA');
INSERT INTO Tracks(title,length,album,url) VALUES ('That Song','03:13:00','ama4','yR05g0Co7W4');
INSERT INTO Tracks(title,length,album,url) VALUES ('21','03:05:00','ama4','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('On the Rocks','03:09:00','ama4','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Limitless','03:10:00','ama4','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Fury','02:58:00','ama4','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Faster','03:25:00','ama4','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Break Down and Cry','03:56:00','ama4','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Supersonic','03:17:00','ama4','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Fireball','03:14:00','ama4','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Endlessly','03:43:00','ama4','null');
