INSERT INTO Albums(id,artist,title,release) VALUES ('pnd1','Pendulum','Hold Your Colour','2005-07-25');
INSERT INTO Albums(id,artist,title,release) VALUES ('pnd2','Pendulum','In Silico','2008-05-12');
INSERT INTO Albums(id,artist,title,release) VALUES ('pnd3','Pendulum','Immersion','2010-05-24');
INSERT INTO Tracks(title,length,album,url) VALUES ('Prelude','00:52:00','pnd1','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Slam','05:44:00','pnd1','gIOQfdn9L9c');
INSERT INTO Tracks(title,length,album,url) VALUES ('Plasticworld','06:21:00','pnd1','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Fasten Your Seatbelt','06:38:00','pnd1','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Through the Loop','06:13:00','pnd1','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Sounds of Life','05:21:00','pnd1','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Girl in the Fire','04:53:00','pnd1','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Tarantula','05:31:00','pnd1','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Out Here','06:07:00','pnd1','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Hold Your Colour','05:28:00','pnd1','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('The Terminal','05:42:00','pnd1','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Streamline','05:23:00','pnd1','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Another Planet','07:38:00','pnd1','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Still Grey','07:51:00','pnd1','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Showdown','05:27:00','pnd2','X6BKBIOtRXw');
INSERT INTO Tracks(title,length,album,url) VALUES ('Different','05:51:00','pnd2','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Propane Nightmares','05:13:00','pnd2','WPbeEtjo70g');
INSERT INTO Tracks(title,length,album,url) VALUES ('Visions','05:36:00','pnd2','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Midnight Runner','06:55:00','pnd2','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('The Other Side','05:15:00','pnd2','zENtEumtyBI');
INSERT INTO Tracks(title,length,album,url) VALUES ('Mutiny','05:09:00','pnd2','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('9,000 Miles','06:26:00','pnd2','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Granite','04:41:00','pnd2','DQA1d0QQvf8');
INSERT INTO Tracks(title,length,album,url) VALUES ('The Tempest','07:27:00','pnd2','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Genesis','01:09:00','pnd3','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Salt in the Wounds','06:38:00','pnd3','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Watercolour','05:04:00','pnd3','tEPB7uzKuh4');
INSERT INTO Tracks(title,length,album,url) VALUES ('Set Me on Fire','05:02:00','pnd3','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Crush','04:13:00','pnd3','8mYd2X_9rrs');
INSERT INTO Tracks(title,length,album,url) VALUES ('Under the Waves','04:54:00','pnd3','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Immunize','04:36:00','pnd3','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('The Island – Pt.I (Dawn)','05:20:00','pnd3','hszZmFRPqx8');
INSERT INTO Tracks(title,length,album,url) VALUES ('The Island – Pt.II (Dusk)','04:09:00','pnd3','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Comprachicos','02:48:00','pnd3','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('The Vulture','04:03:00','pnd3','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Witchcraft','04:12:00','pnd3','ogMNV33AhCY');
INSERT INTO Tracks(title,length,album,url) VALUES ('Self vs. Self','04:45:00','pnd3','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('The Fountain','05:00:00','pnd3','null');
INSERT INTO Tracks(title,length,album,url) VALUES ('Encoder','05:21:00','pnd3','null');
